# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b98a7e12daa80ec3778f910e9891001df150dd10e5d4056dd4c166d706937fe08586aca1f41cc4859e91f626e7b60ef93fa2f633a974b8b2fdf7fee86bdf51f

test:
  secret_key_base: cd7ad96b7cd4215b72bcb404d9723176719ae70c97c8e2b3a12eb378a9dd1024509d5aba7371f537403cb90751692afaa1dec876419fddb50f421ab4615d0e46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
